In [3]:
import pandas as pd
import numpy as np
import json
from IPython.display import Image
from IPython.core.display import HTML

In [4]:
city = pd.read_csv('city.csv')

Посчитали количество строк в таблице "city", и время выполнения запроса

In [5]:
%%time
len(city)

Wall time: 0 ns

1117

Узнали самое длинное название города в таблице

In [7]:
%%time
list=[]
for c in city["city"]:
    c = str(c)
    list.append(c)
print("Длина: ", len(max(list, key=len)), "\nСлово: ", max(list, key=len))

Длина:  25
Слово:  Александровск-Сахалинский
Wall time: 997 µs

Написали запрос, который посчитал кол-во городов для каждого часового пояса в Сибирском и Приволжском федеральных округах. Значение timezone(UTC +5) для city_count = 58

In [26]:
k = city[city['federal_district'].isin(['Приволжский', 'Сибирский'])]
k[['timezone','country']].groupby('timezone').count().rename({'country': 'city_count'}, axis=1)

          city_count
timezone
UTC+3            101
UTC+4             41
UTC+5             58
UTC+6              6
UTC+7             86
UTC+8             22

Решили задачу: написали  запрос, который посчитал кол-во городов в каждом часовом поясе. Отсортировали по кол-ву городов по убыванию.

In [28]:
k = city[['timezone','address']].groupby('timezone').count().sort_values('address', ascending=False)
k.rename({'address': 'city_count'}, axis=1)

          city_count
timezone
UTC+3            660
UTC+5            173
UTC+7             86
UTC+4             66
UTC+9             31
UTC+8             28
UTC+10            22
UTC+2             22
UTC+11            17
UTC+12             6
UTC+6              6

Выбрали свою таблицу, и произвели те же запросы, что и в sqlite

In [29]:
cacao = pd.read_csv('cacao.csv')

In [56]:
k = cacao[cacao['CocoaPercent'] == '63%']
k[['CompanyLocation', 'CocoaPercent']]

     CompanyLocation CocoaPercent
0             France          63%
20            France          63%
22            France          63%
72            Canada          63%
85             Italy          63%
321          Ecuador          63%
879   Czech Republic          63%
992       Madagascar          63%
1093          U.S.A.          63%
1152         Ecuador          63%
1676          France          63%
1682          France          63%

In [54]:
k = cacao[['Company','ReviewDate']].sort_values('ReviewDate', ascending=False)
k.rename({'ReviewDate': 'Count'}, axis=1)

                     Company  Count
1476  Smooth Chocolator, The   2017
958              Letterpress   2017
1559                    Soul   2017
535              Dick Taylor   2017
1567                 Spencer   2017
...                      ...    ...
769                 Guittard   2006
770                 Guittard   2006
878            Jacque Torres   2006
1443        Scharffen Berger   2006
576                   Domori   2006

[1795 rows x 2 columns]

In [1]:
k = cacao[cacao['BeanType'].isin(['Trinitario'])]
k = k[['CompanyLocation','BeanType', 'Rating']].sort_values('Rating', ascending=False)
k.to_csv('out.csv' ,encoding='utf-8', index=False, sep='|')

NameError: name 'cacao' is not defined

In [75]:
k = cacao[cacao['Rating'] == 3.25]
k = k[['CompanyLocation','BeanType', 'Rating']]
result = k.to_json(orient="records")
parsed = json.loads(result)
parsed

[{'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Fiji', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Peru', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Brazil',
  'BeanType': 'Forastero (Catongo)',
  'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Switzerland', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Switzerland',
  'BeanType': 'Criollo (Porcelana)',
  'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador',
  'BeanType': 'Forastero (Arriba)',
  'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Russia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Blend', 'Rating': 3.25},
 {'CompanyLocation': 'Venezuela', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Venezuela', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Venezuela', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Colombia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Spain', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Japan', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Peru', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador',
  'BeanType': 'Forastero (Arriba)',
  'Rating': 3.25},
 {'CompanyLocation': 'Costa Rica', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Colombia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Colombia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Germany', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Amsterdam', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Scotland', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Spain', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Spain', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Spain', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Argentina', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Argentina', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Germany',
  'BeanType': 'Forastero (Nacional)',
  'Rating': 3.25},
 {'CompanyLocation': 'Germany', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Germany', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Germany',
  'BeanType': 'Criollo (Ocumare 61)',
  'Rating': 3.25},
 {'CompanyLocation': 'Germany', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.',
  'BeanType': 'Forastero (Nacional)',
  'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Guatemala', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Guatemala', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Guatemala', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Italy',
  'BeanType': 'Criollo (Ocumare 61)',
  'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'St. Lucia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Spain', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Denmark', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Denmark', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Denmark',
  'BeanType': 'Criollo, Trinitario',
  'Rating': 3.25},
 {'CompanyLocation': 'Denmark',
  'BeanType': 'Criollo, Trinitario',
  'Rating': 3.25},
 {'CompanyLocation': 'Denmark',
  'BeanType': 'Criollo, Trinitario',
  'Rating': 3.25},
 {'CompanyLocation': 'Denmark',
  'BeanType': 'Criollo, Trinitario',
  'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Germany', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Grenada', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Amazon', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'New Zealand', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador',
  'BeanType': 'Forastero (Arriba) ASS',
  'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada',
  'BeanType': 'Trinitario, Criollo',
  'Rating': 3.25},
 {'CompanyLocation': 'Switzerland', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Domincan Republic', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Domincan Republic', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Poland', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Poland', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Vietnam', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Austria', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Honduras', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Honduras', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Nicaragua', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Lithuania', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.',
  'BeanType': 'Forastero (Nacional)',
  'Rating': 3.25},
 {'CompanyLocation': 'Nicaragua',
  'BeanType': 'Forastero (Nacional)',
  'Rating': 3.25},
 {'CompanyLocation': 'New Zealand', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Switzerland', 'BeanType': 'Blend', 'Rating': 3.25},
 {'CompanyLocation': 'Switzerland', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Belgium', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'Belgium', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France',
  'BeanType': 'Criollo (Porcelana)',
  'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'U.K.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Brazil', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Brazil', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Brazil', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'France', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Ecuador', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.',
  'BeanType': 'Nacional (Arriba)',
  'Rating': 3.25},
 {'CompanyLocation': 'South Korea', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'South Korea', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'South Korea', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Madagascar', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Madagascar', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.',
  'BeanType': 'Criollo, Trinitario',
  'Rating': 3.25},
 {'CompanyLocation': 'Peru', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Costa Rica', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'Italy', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Australia', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'New Zealand', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'New Zealand', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Blend', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Criollo', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': 'Forastero', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Canada', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Switzerland', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Hungary', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Japan', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'Japan', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'Suriname', 'BeanType': 'Trinitario', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': '\xa0', 'Rating': 3.25},
 {'CompanyLocation': 'U.S.A.', 'BeanType': 'Forastero', 'Rating': 3.25},

In [77]:
k = cacao[cacao['Rating'].between(3, 5)]
k[['Company', 'Rating']]

       Company  Rating
0     A. Morin    3.75
2     A. Morin    3.00
3     A. Morin    3.50
4     A. Morin    3.50
6     A. Morin    3.50
...        ...     ...
1790    Zotter    3.75
1791    Zotter    3.00
1792    Zotter    3.50
1793    Zotter    3.25
1794    Zotter    3.00

[1346 rows x 2 columns]